###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: "policy-hub"

# -- Provide centralidp base address (CX IAM), without trailing '/auth'.
centralidpAddress: "https://centralidp.example.org"

backend:
  ingress:
    # -- Policy Hub ingress parameters,
    # enable ingress record generation for policy-hub.
    enabled: false
    name: "policy-hub"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      # -- Provide CORS allowed origin.
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.example.org"
    tls:
      # -- Provide tls secret.
      - secretName: ""
        # -- Provide host for tls secret.
        hosts:
          - ""
    hosts:
      # -- Provide default path for the ingress record.
      - host: "policy-hub.example.org"
        paths:
          - path: "/api/hub"
            pathType: "Prefix"
            backend:
              service: "policy-hub-service"
              port: 8080
  dotnetEnvironment: "Production"
  dbConnection:
    schema: "hub"
    sslMode: "Disable"
  keycloak:
    central:
      authRealm: "CX-Central"
      jwtBearerOptions:
        requireHttpsMetadata: "true"
        metadataPath: "/auth/realms/CX-Central/.well-known/openid-configuration"
        tokenValidationParameters:
          validIssuerPath: "/auth/realms/CX-Central"
          validAudience: "ClXX-CX-Policy-Hub"
        refreshInterval: "00:00:30"
      tokenPath: "/auth/realms/CX-Central/protocol/openid-connect/token"
      # -- Flag if the api should be used with an leading /auth path
      useAuthTrail: true
  healthChecks:
    startup:
      path: "/health/startup"
    liveness:
      path: "/healthz"
    readyness:
      path: "/ready"
  policyhub:
    name: "policy-hub-service"
    image:
      name: "tractusx/policy-hub-service"
      policyhubservicetag: 29dbdeb9a8b3e809fdab2406140a226bc55de844
    # -- We recommend not to specify default resources and to leave this as a conscious choice for the user.
    # If you do want to specify resources, uncomment the following lines,
    # adjust them as necessary, and remove the curly braces after 'resources:'.
    resources: {}
      # limits:
      #   cpu: 250m
      #   memory: 256Mi
      # requests:
      #   cpu: 250m
      #   memory: 256Mi
    logging:
      businessLogic: "Information"
      default: "Information"
    keycloakClientId: "ClXX-CX-Policy-Hub"
  policyhubmigrations:
    name: "policy-hub-migrations"
    image:
      name: "tractusx/policy-hub-migrations"
      policyhubmigrationstag: 29dbdeb9a8b3e809fdab2406140a226bc55de844
    # -- We recommend not to specify default resources and to leave this as a conscious choice for the user.
    # If you do want to specify resources, uncomment the following lines,
    # adjust them as necessary, and remove the curly braces after 'resources:'.
    resources: {}
      # limits:
      #   cpu: 250m
      #   memory: 256Mi
      # requests:
      #   cpu: 250m
      #   memory: 256Mi
    seeding:
      testDataEnvironments: ""
      # -- when changing the testDataPath the processIdentity needs to be adjusted as well,
      # or it must be ensured that the identity is existing within the files under the new path
      testDataPaths: "Seeder/Data"
    logging:
      default: "Information"

postgresql:
# -- PostgreSQL chart configuration
  # Switch to enable or disable the PostgreSQL helm chart
  enabled: true
  # -- FullnameOverride to 'policy-hub-postgresql'.
  fullnameOverride: "policy-hub-postgresql"
  auth:
    # -- Database name
    database: "postgres"
    # -- Database port number
    port: 5432
    # -- Secret containing the passwords for root usernames postgres and non-root usernames repl_user and hub.
    existingSecret: "secret-postgres-init"
    # -- Password for the root username 'postgres'. Secret-key 'postgres-password'.
    password: ""
    # -- Non-root username for hub.
    policyHubUser: "hub"
    # -- Password for the non-root username 'hub'. Secret-key 'policy-hub-password'.
    policyHubPassword: ""
  architecture: "replication"
  audit:
    pgAuditLog: "write, ddl"
    logLinePrefix: "%m %u %d "
  primary:
    # -- Extended PostgreSQL Primary configuration (increase of max_connections recommended - default is 100)
    extendedConfiguration: ""
    initdb:
      scriptsConfigMap: "configmap-postgres-init"
    extraEnvVars:
      - name: "POLICY_HUB_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.auth.existingSecret }}"
            key: "policy-hub-password"
  readReplicas:
  # -- Extended PostgreSQL read only replicas configuration (increase of max_connections recommended - default is 100)
    extendedConfiguration: ""

externalDatabase:
# -- External PostgreSQL configuration
# IMPORTANT: init scripts (01-init-db-user.sh and 02-init-db.sql) available
# in templates/configmap-backend-postgres-init.yaml need to be executed beforehand.
  # Database host
  host: "policy-hub-postgresql-external-db"
  # -- Database name
  database: "postgres"
  # -- Database port number
  port: 5432
  # -- Secret containing the passwords non-root username hub.
  secret: "secret-postgres-external-db"
  # -- Non-root username for hub.
  policyHubUser: "hub"
  # -- Password for the non-root username 'hub'. Secret-key 'policy-hub-password'.
  policyHubPassword: ""

portContainer: 8080

portService: 8080

replicaCount: 3

# -- Node labels for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

affinity:
# -- Following Catena-X Helm Best Practices,
# [reference](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: DoesNotExist
          topologyKey: kubernetes.io/hostname

updateStrategy:
# -- Update strategy type,
# rolling update configuration parameters,
# [reference](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies).
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# -- Following Catena-X Helm Best Practices,
# [reference](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210).
startupProbe:
  failureThreshold: 30
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
