
###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: Release tag and changelog

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/v*.*.*'

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  # Run the workflow only if the PR was merged, if it was rejected or closed we don't want to create the tags
  release-rc:
    if: github.event.pull_request.merged == true && startsWith(github.ref_name, 'refs/heads/release/v*-RC')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Change","hidden":false},{"type":"fix","section":"Bugfix","hidden":false},{"type":"chore","section":"Technical Support","hidden":false}]'
          pull-request-header: 'New release was created'
          prerelease: true

  # Run the workflow only if the PR was merged, if it was rejected or closed we don't want to create the tags
  release:
    if: github.event.pull_request.merged == true && !startsWith(github.ref_name, 'refs/heads/release/v*-RC')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Change","hidden":false},{"type":"fix","section":"Bugfix","hidden":false},{"type":"chore","section":"Technical Support","hidden":false}]'
          pull-request-header: 'New release was created'
      - uses: actions/checkout@v2
      - name: tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name eclipse-tractusx-bot
          git config user.email tractusx-bot@eclipse.org
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{github.event.repository.name}}.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Version v${{ steps.release.outputs.major }}: Catena-X Policy Hub"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Version v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}: Catena-X Policy Hub"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}